# Generated by Django 2.2 on 2019-04-18 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_created', models.DateTimeField(verbose_name='date file created')),
                ('file_number', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=400)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='votes',
            fields=[
                ('person', models.CharField(max_length=20)),
                ('vote', models.CharField(max_length=5)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_record_ui.MetaTable')),
            ],
        ),
        migrations.CreateModel(
            name='PassedLegislation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_Details', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=100)),
                ('Action_By', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(verbose_name='date passed')),
                ('Version', models.IntegerField(default=0)),
                ('file_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_record_ui.MetaTable')),
            ],
        ),
        migrations.CreateModel(
            name='all_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_Details', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=100)),
                ('Action_By', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(verbose_name='date passed')),
                ('Version', models.IntegerField(default=0)),
                ('file_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_record_ui.MetaTable')),
            ],
        ),
    ]
