# Generated by Django 2.2 on 2019-04-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_record_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatable',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
