# Generated by Django 2.2 on 2019-04-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_record_ui', '0002_auto_20190418_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_links',
            name='Action',
            field=models.CharField(max_length=300),
        ),
    ]
