# Generated by Django 2.2 on 2019-04-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_record_ui', '0003_auto_20190418_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_links',
            name='A_Details',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='all_links',
            name='Action',
            field=models.TextField(blank=True, null=True, verbose_name='action'),
        ),
    ]
