# Generated by Django 2.2 on 2019-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_record_ui', '0005_auto_20190418_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_links',
            name='Date',
            field=models.DateTimeField(blank=True, verbose_name='date passed'),
        ),
    ]
