# Generated by Django 2.2 on 2019-04-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_record_ui', '0007_auto_20190418_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_links',
            name='file_number',
            field=models.IntegerField(default=0),
        ),
    ]
