# Generated by Django 2.2 on 2019-04-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_record_ui', '0008_auto_20190418_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passedlegislation',
            name='A_Details',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='passedlegislation',
            name='Action',
            field=models.TextField(blank=True, null=True, verbose_name='action'),
        ),
    ]
