# Generated by Django 2.2 on 2019-04-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_record_ui', '0009_auto_20190418_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passedlegislation',
            name='file_number',
            field=models.IntegerField(default=0),
        ),
    ]
