# Generated by Django 2.2 on 2019-04-18 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting_record_ui', '0010_auto_20190418_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='file_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_record_ui.PassedLegislation'),
        ),
    ]
