# Generated by Django 2.2 on 2019-04-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_record_ui', '0011_auto_20190418_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
