# Generated by Django 2.2 on 2019-04-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_record_ui', '0012_auto_20190418_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
