# Generated by Django 2.2 on 2019-04-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_record_ui', '0013_auto_20190418_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='vote',
            field=models.CharField(max_length=10),
        ),
    ]
